import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useEffect } from "react";
import axios from "axios";
import { useState } from "react";

import Papa from "papaparse";
import dayjs from "dayjs";
var customParseFormat = require('dayjs/plugin/customParseFormat');

dayjs.extend(customParseFormat)

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const getLibVersion = async (lib) => {
    return await axios.get(`/api/getlatest/${lib}`).then((res) => res.data);
  };

  const getLatestVersion = async (keys) => {
    const lib = keys;

    return await Promise.all(
      lib.map(async (lib) => {
        let pack = lib;

        if (pack.includes("/")) {
          pack = pack.replace("/", "|");
        }

        return await getLibVersion(pack);
      })
    );
  };

  const handleDownload = () => {
    if (!data) return;

    var dt = Papa.unparse(data);

    var blob =
      dt.constructor !== Blob
        ? new Blob([dt], { type: "application/octet-stream" })
        : dt;

    if (navigator.msSaveBlob) {
      navigator.msSaveBlob(blob, "package.csv");
      return;
    }

    var lnk = document.createElement("a"),
      url = window.URL,
      objectURL;

    lnk.download = "package.csv";
    lnk.href = objectURL = url.createObjectURL(blob);
    lnk.dispatchEvent(new MouseEvent("click"));
    setTimeout(url.revokeObjectURL.bind(url, objectURL));
  };

  const handleUpload = (e) => {
    setLoading(true);

    const file = e.target.files[0];
    const reader = new FileReader();
    reader.readAsText(file);
    reader.onload = async (e) => {
      const json = JSON.parse(e.target.result);

      const { dependencies, devDependencies } = json;

      let depKeys = Object.keys(dependencies);
      let depDevKeys = Object.keys(devDependencies);

      let val = await getLatestVersion(depKeys);

      var depArray = [];

      depKeys.forEach((element) => {
        depArray.push({
          package: element,
          current: dependencies[element],
          latest: val.filter((x) => x.package == element)[0].version,
          release: val.filter((x) => x.package == element)[0].release,
          url: val.filter((x) => x.package == element)[0].url,
        });
      });

      setLoading(false);
      setData(depArray);
    };
  };

  return (
    <>
      <Head>
        <title>Is My Packages Latest?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid min-h-full place-items-center py-24 px-6 sm:py-32 lg:px-8 text-white">
        <div className="text-center ">
          <p className="inline bg-gradient-to-r from-indigo-200 via-sky-400 to-indigo-200 bg-clip-text font-display text-5xl tracking-tight text-transparent">
            Is My Packages Latest?
          </p>

          <div className="mt-6 text-base leading-7 text-white">
            <h1>Import Package.json</h1>
            <input disabled={loading && true} type="file" onChange={handleUpload} />
          </div>

          <div className="my-4 text-base tracking-tight text-white-900">
            {data.length > 0 && (
              <button
                className="mt-10 bg-indigo-500 text-white px-4 py-2 rounded"
                onClick={handleDownload}
              >
                Download Report
              </button>
            )}

            {loading && <div className="text-white">Loading...</div>}

            {data.length > 0 && (
              <table className="table-auto text-white">
                <thead>
                  <tr>
                    <th className="px-4 py-2">Package</th>
                    <th className="px-4 py-2">Current</th>
                    <th className="px-4 py-2">Latest</th>
                    <th className="px-4 py-2">Release date</th>
                    <th className="px-4 py-2">Url</th>
                  </tr>
                </thead>
                <tbody>
                  {data.map((x, index) => (
                    <tr key={index}>
                      <td className="border px-4 py-2">{x.package}</td>
                      <td
                        className={`border px-4 py-2 ${x.current.replace("^", "") !== x.latest &&
                          "text-red-500"
                          }`}
                      >
                        {x.current}
                      </td>
                      <td className="border px-4 py-2">{x.latest}</td>
                      <td className="border px-4 py-2">{
                        x.release ? dayjs(x.release, "YYYY-MM-DD").format("DD MMM YYYY") : "-"
                      }</td>
                      <td className="border px-4 py-2">
                        <a href={x.url} target={"_blank"} rel={"noreferrer"}>{x.url}</a>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
